version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1110:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /usr/share/nginx/html
      - ./public/contents:/usr/share/nginx/html/contents:ro
      
    environment:
      - NODE_ENV=production
    restart: unless-stopped